freakdaddy/freakdaddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

freakdaddy/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('tasks/', views.about, name='tasks'),
    path('add_task/', views.add_task, name='add_task')
]

freakdaddy/main/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField('Title', max_length=100)
    text = models.TextField('Text')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

freakdaddy/main/forms.py
from typing import Text
from .models import Task
from django.forms import ModelForm, TextInput, Textarea

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'text']
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Input title',
                'style': 'width: 200px;'
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Input description',
                'style': 'width: 650px; height: 200px'
            })
        }

freakdaddy/main/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm

# Create your views here.
def index(request):
    template = 'main/index.html'
    return render(request, template)

def about(request):
    title = 'Add task'
    tasks = Task.objects.all().order_by('-text')
    context = {
        'tasks': tasks,
        'title': title,
    }
    template = 'main/tasks.html'
    return render(request, template, context)

def add_task(request):
    error = ''
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:tasks')
        else:
            error = 'Форма неверна'

    form = TaskForm()
    context = {
        'form': form,
        'error': error,
    }
    template = 'main/add_task.html'
    return render(request, template, context)

freakdaddy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <title>{% block title %}---{% endblock %}</title>
</head>
{% include 'includes/header.html'%}
<main class="">
    <body class="text-bg-dark">
    {% block content %}
        Контента нет
    {% endblock %}
</main>
</html>

freakdaddy/templates/includes/header.html
<header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'main:index'%}" class="nav-link active rounded-pill" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="{% url 'main:tasks'%}" class="nav-link active text-white bg-secondary rounded-pill">Tasks</a></li>
      <li class="nav-item"><a href="{% url 'main:add_task'%}" class="nav-link active text-white rounded-pill bg-secondary">Add Task</a></li>
    </ul>
</header>

freakdaddy/templates/main/add_task.html
{% extends "base.html" %}
{% block title %}Add task{% endblock %}
{% block content %}
<div class='position-absolute top-50 start-50 translate-middle'>
  <h1>Add task</h1>
  <form method='post'>
    {% csrf_token %}
    {{ form.title }}<br>
    {{ form.text }}<br>
    <button type='submit' class='btn btn-success rounded text-white'>Add</button>
    <span>{{ error }}</span>
  </form>
</div>
{% endblock %}

freakdaddy/templates/main/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<main class='position-absolute top-50 start-50 translate-middle'>
  <h1>
    Это сайт для добавления задач
  </h1>
  <p>Нажмите на кнопку Tasks, что бы посмотреть задачи. Что бы добавить задачу нажмите Add Task</p>
</maim>
{% endblock %}
</html>

freakdaddy/templates/main/tasks.html
{% extends "base.html" %}
{% block title %}Tasks{% endblock %}
{% block content %}
<div style='position: absolute; left: 39%; top: 10%;'>
{% if tasks %}
  {% for el in tasks %}
  <div class='alert bg-secondary mt-2  text-center rounded' style='width: 400px;'>
      <h3>{{ el.title }}</h3>
      <p>{{ el.text }}</p>
  </div>
  {% endfor %}
  {% else %}
  <p>Задач нет</p>
  {% endif %}
</div>
{% endblock %}